=== molstar/molstar-volseg/preprocessor/cellstar_preprocessor/model/preprocessor_params.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "quantize_downsampling_levels": {
            "type": [
                "array",
                "null"
            ],
            "items": {
                "type": "number"
            },
            "minItems": 1
        },
        "mode": {
            "type": "string",
            "enum": [
                "add",
                "extend"
            ]
        },
        "quantize_dtype_str": {
            "type": [
                "string",
                "null"
            ],
            "enum": [
                "u1",
                "u2"
            ]
        },
        "force_volume_dtype": {
            "type": [
                "string",
                "null"
            ]
        },
        "max_size_per_downsampling_lvl_mb": {
            "type": [
                "number",
                "null"
            ]
        },
        "min_size_per_downsampling_lvl_mb": {
            "type": [
                "number",
                "null"
            ]
        },
        "min_downsampling_level": {
            "type": [
                "integer",
                "null"
            ]
        },
        "max_downsampling_level": {
            "type": [
                "integer",
                "null"
            ]
        },
        "remove_original_resolution": {
            "type": [
                "boolean",
                "null"
            ]
        },
        "entry_id": {
            "type": "string"
        },
        "source_db": {
            "type": "string"
        },
        "source_db_id": {
            "type": "string"
        },
        "source_db_name": {
            "type": "string"
        },
        "working_folder": {
            "type": "string"
        },
        "db_path": {
            "type": "string"
        },
        "inputs": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string"
                    },
                    "kind": {
                        "type": "string",
                        "enum": [
                            "map",
                            "sff",
                            "omezarr",
                            "mask",
                            "wrl",
                            "stl",
                            "seg",
                            "am",
                            "custom_annotations",
                            "nii_volume",
                            "nii_segmentation",
                            "geometric_segmentation",
                            "ometiff_image",
                            "ometiff_segmentation",
                            "extra_data",
                            "tiff_image_stack_dir",
                            "tiff_segmentation_stack_dir"
                        ]
                    },
                    "parameters": {
                        "type": ["object", "null"],
                        "properties": {
                            "pre_downsampling_factor": {
                                "type": "integer"
                            }
                        }
                    }
                }
            },
            "minItems": 1
        }
    },
    "additionalProperties": false
}

=== molstar/molstar-volseg/preprocessor/cellstar_preprocessor/model/actin_params.json
{   
    "$schema": "preprocessor_params.schema.json",
    "db_path": "preprocessor/temp/test_db",
    "entry_id": "custom-actin",
    "source_db": "custom",
    "inputs": [
        {
            "kind": "ometiff_image",
            "path": "PC-3_control_F01.tif",
            "parameters": {
                "pre_downsampling_factor": 8
            }
        },
        {
            "kind": "wrl",
            "path": "actin.wrl",
            "parameters": {
                "pre_downsampling_factor": 32
            }
        }
    ],
    "mode": "add",
    "source_db_id": "actin",
    "source_db_name": "custom",
    "working_folder": "preprocessor/temp/working_folder"
}

=== molstar/molstar-volseg/preprocessor/cellstar_preprocessor/model/cellim_params.json
{   
    "$schema": "preprocessor_params.schema.json",
    "db_path": "preprocessor/temp/test_db",
    "entry_id": "custom-cellim",
    "source_db": "custom",
    "inputs": [
        {
            "kind": "ometiff_image",
            "path": "PC-3_control_F01.tif",
            "parameters": {
                "pre_downsampling_factor": 4
            }
        },
        {
            "kind": "wrl",
            "path": "actin.wrl",
            "parameters": {
                "pre_downsampling_factor": 32
            }
        },
        {
            "kind": "wrl",
            "path": "tubulin.wrl",
            "parameters": {
                "pre_downsampling_factor": 32
            }
        },
        {
            "kind": "wrl",
            "path": "nucleus.wrl",
            "parameters": {
                "pre_downsampling_factor": 32
            }
        }
    ],
    "mode": "extend",
    "source_db_id": "cellim",
    "source_db_name": "custom",
    "working_folder": "preprocessor/temp/working_folder"
}

=== molstar/molstar-volseg/preprocessor/cellstar_preprocessor/model/sample_preprocessor_params.json
{
    "$schema": "preprocessor_params.schema.json",
    "db_path": "preprocessor/temp/test_db",
    "entry_id": "emd-1832",
    "source_db": "emdb",
    "force_volume_dtype": "f4",
    "inputs": [
        {
            "kind": "map",
            "path": "test-data/preprocessor/sample_volumes/emdb/EMD-1832.map"
        },
        {
            "kind": "sff",
            "path": "test-data/preprocessor/sample_segmentations/emdb_sff/emd_1832.hff"
        }
    ],
    "max_downsampling_level": 8,
    "max_size_per_downsampling_lvl_mb": 40.0,
    "min_downsampling_level": 4,
    "min_size_per_downsampling_lvl_mb": 12.0,
    "mode": "add",
    "quantize_downsampling_levels": [1, 4],
    "quantize_dtype_str": "u2",
    "remove_original_resolution": true,
    "source_db_id": "emd-1832",
    "source_db_name": "emdb",
    "working_folder": "preprocessor/temp/working_folder"
}
